In [42]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import mean_squared_error as MSE
from sklearn.metrics import mean_absolute_error as MAE
from sklearn.metrics import r2_score

In [49]:
# 엑셀 파일 불러오기
df = pd.read_csv('melb_included_regionname.csv')

In [50]:
print(df.info())
df.head()

df = df.drop(columns = ['date'])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 26 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   rooms                                  13580 non-null  int64
 1   price                                  13580 non-null  float64
 2   date                                   13580 non-null  object
 3   distance                               13580 non-null  float64
 4   bedroom2                               13580 non-null  float64
 5   bathroom                               13580 non-null  float64
 6   car                                    13580 non-null  float64
 7   landsize                               13580 non-null  float64
 8   propertycount                          13580 non-null  float64
 9   type_h                                 13580 non-null  int64
 10  type_t                                 13580 non-null  int64
 11  type_u                                 13580 non-null  int64
 12  method_pi                              13580 non-null  int64
 13  method_s                               13580 non-null  int64
 14  method_sa                              13580 non-null  int64
 15  method_sp                              13580 non-null  int64
 16  method_vb                              13580 non-null  int64
 17  month                                  13580 non-null  float64
 18  regionname_Eastern Metropolitan        13580 non-null  bool
 19  regionname_Eastern Victoria            13580 non-null  bool
 20  regionname_Northern Metropolitan       13580 non-null  bool
 21  regionname_Northern Victoria           13580 non-null  bool
 22  regionname_South-Eastern Metropolitan  13580 non-null  bool
 23  regionname_Southern Metropolitan       13580 non-null  bool
 24  regionname_Western Metropolitan        13580 non-null  bool
 25  regionname_Western Victoria            13580 non-null  bool
dtypes: bool(8), float64(8), int64(9), object(1)
memory usage: 2.0+ MB
None

In [53]:
for i in range(0, len(df)) :
    df.loc[i, ['price']] = np.log(df.loc[i, ['price']])

TypeError: loop of ufunc does not support argument 0 of type numpy.float64 which has no callable log method

## 최종 dataframe

In [45]:
from sklearn.preprocessing import MinMaxScaler


scaler = MinMaxScaler()
df = pd.DataFrame(scaler.fit_transform(df), columns=df.columns)

In [46]:
df

,rooms,price,distance,bedroom2,bathroom,car,landsize,propertycount,type_h,type_t,...,method_vb,month,regionname_Eastern Metropolitan,regionname_Eastern Victoria,regionname_Northern Metropolitan,regionname_Northern Victoria,regionname_South-Eastern Metropolitan,regionname_Southern Metropolitan,regionname_Western Metropolitan,regionname_Western Victoria
0,0.111111,0.156478,0.051975,0.10,0.125,0.1,0.000466,0.176160,1.0,0.0,...,0.0,0.181818,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,0.111111,0.106562,0.051975,0.10,0.125,0.0,0.000360,0.176160,1.0,0.0,...,0.0,0.272727,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,0.222222,0.154795,0.051975,0.15,0.250,0.0,0.000309,0.176160,1.0,0.0,...,0.0,0.272727,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,0.222222,0.085810,0.051975,0.15,0.250,0.1,0.000217,0.176160,1.0,0.0,...,0.0,0.272727,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,0.333333,0.169938,0.051975,0.15,0.125,0.2,0.000277,0.176160,1.0,0.0,...,1.0,0.272727,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,0.333333,0.130118,0.347193,0.20,0.250,0.2,0.001506,0.333769,1.0,0.0,...,0.0,0.636364,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
13576,0.222222,0.106113,0.141372,0.15,0.250,0.2,0.000769,0.286482,1.0,0.0,...,0.0,0.636364,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
13577,0.222222,0.121705,0.141372,0.15,0.250,0.4,0.001007,0.286482,1.0,0.0,...,0.0,0.636364,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
13578,0.333333,0.270892,0.141372,0.20,0.125,0.5,0.002000,0.286482,1.0,0.0,...,0.0,0.636364,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
13579,0.333333,0.134605,0.130977,0.20,0.125,0.1,0.000836,0.294098,1.0,0.0,...,0.0,0.636364,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [9]:
df.describe()

,rooms,price,distance,bedroom2,bathroom,car,landsize,propertycount,type_h,type_t,type_u,method_pi,method_s,method_sa,method_sp,method_vb,month
count,13580.000000,1.358000e+04,13580.000000,13580.000000,13580.000000,13580.000000,13580.000000,13580.000000,13580.000000,13580.000000,13580.000000,13580.000000,13580.000000,13580.000000,13580.000000,13580.000000,13580.000000
mean,2.937997,1.075684e+06,10.137776,2.914728,1.534242,1.609884,558.416127,7454.417378,0.695803,0.082032,0.222165,0.115169,0.664359,0.006775,0.125405,0.088292,6.701988
std,0.955748,6.393107e+05,5.868725,0.965921,0.691712,0.960464,3990.669241,4378.581772,0.460084,0.274424,0.415717,0.319238,0.472231,0.082032,0.331190,0.283729,2.758499
min,1.000000,8.500000e+04,0.000000,0.000000,0.000000,0.000000,0.000000,249.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,2.000000,6.500000e+05,6.100000,2.000000,1.000000,1.000000,177.000000,4380.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000
50%,3.000000,9.030000e+05,9.200000,3.000000,1.000000,2.000000,440.000000,6555.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,7.000000
75%,3.000000,1.330000e+06,13.000000,3.000000,2.000000,2.000000,651.000000,10331.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,9.000000
max,10.000000,9.000000e+06,48.100000,20.000000,8.000000,10.000000,433014.000000,21650.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,12.000000

# Analysis

In [12]:
def adj_R2(real, pred, X) :
    Adj_r2 = 1 - (1 - r2_score(real, pred)) * (len(real) - 1)/(len(real) - X.shape[1]-1)
    return Adj_r2

In [19]:
from sklearn import linear_model
from xgboost import XGBRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LassoCV
from sklearn.neighbors import KNeighborsRegressor

In [22]:
X_test

,rooms,date,distance,bedroom2,bathroom,car,landsize,propertycount,type_h,type_t,...,method_vb,month,regionname_Eastern Metropolitan,regionname_Eastern Victoria,regionname_Northern Metropolitan,regionname_Northern Victoria,regionname_South-Eastern Metropolitan,regionname_Southern Metropolitan,regionname_Western Metropolitan,regionname_Western Victoria
1061,3,6/08/2016,11.2,3.0,2.0,3.0,588.0,10579.0,1,0,...,0,6.0,False,False,False,False,False,True,False,False
6482,2,28/05/2016,1.9,2.0,1.0,1.0,0.0,2230.0,0,0,...,0,5.0,False,False,True,False,False,False,False,False
8395,3,22/04/2017,6.1,3.0,1.0,0.0,0.0,13240.0,0,0,...,0,4.0,False,False,False,False,False,True,False,False
4659,3,18/06/2016,9.9,3.0,2.0,1.0,146.0,7485.0,0,1,...,1,6.0,False,False,True,False,False,False,False,False
7386,2,24/09/2016,9.1,2.0,1.0,2.0,462.0,984.0,1,0,...,0,9.0,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10455,3,27/05/2017,21.5,3.0,1.0,2.0,545.0,5087.0,1,0,...,0,5.0,False,False,False,False,True,False,False,False
3616,6,13/08/2016,5.6,6.0,6.0,3.0,1334.0,10331.0,1,0,...,0,8.0,False,False,False,False,False,True,False,False
577,5,28/05/2016,9.7,4.0,2.0,2.0,981.0,5682.0,1,0,...,0,5.0,False,False,False,False,False,True,False,False
12620,6,9/09/2017,14.7,6.0,3.0,3.0,754.0,7082.0,1,0,...,0,9.0,True,False,False,False,False,False,False,False
4993,3,25/02/2017,8.8,3.0,1.0,2.0,399.0,14577.0,1,0,...,0,2.0,False,False,True,False,False,False,False,False

In [23]:
#train-test split
from sklearn.model_selection import train_test_split

y = df['price']
X = df.drop(columns = ['price', 'date'])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

### Linear Regression

In [25]:
linearReg = linear_model.LinearRegression()
linearReg.fit(X_train, y_train)

# 테스트 세트로 예측
y_pred = linearReg.predict(X_test)

# 모델 평가
print(MSE(y_test, y_pred))
print(MAE(y_test, y_pred))
#print(r2_score(y_test, y_pred), adj_R2(y_test, y_pred, X_test))

161802452578.69525
276349.13688198687

### LassoCV

In [ ]:
linearLassoReg = LassoCV(random_state = 42)
linearLassoReg.fit(X_train, y_train)

# 테스트 세트로 예측
y_pred = linearLassoReg.predict(X_test)

# 모델 평가
print(MSE(y_test, y_pred))
print(MAE(y_test, y_pred))
#print(r2_score(y_test, y_pred), adj_R2(y_test, y_pred, X_test))

0.540329413621414
0.3834113415776813

In [ ]:
linearLassoReg = LassoCV(random_state = 42)
linearLassoReg.fit(mmX_train, mmy_train)

# 테스트 세트로 예측
mmy_pred = linearLassoReg.predict(mmX_test)

# 모델 평가
print(MSE(mmy_test, mmy_pred))
print(MAE(mmy_test, mmy_pred))
#print(r2_score(y_test, y_pred), adj_R2(y_test, y_pred, X_test))

0.540329413621414
0.3834113415776813

### K-NN

In [ ]:
NNReg_param = {'n_neighbors':[x for x in range(1, 21)]}

NNReg = KNeighborsRegressor()
NNReg_grid = GridSearchCV(NNReg, NNReg_param, cv = 5, refit = True)

NNReg_grid.fit(X_train, y_train)
NNReg = NNReg_grid.best_estimator_
print(NNReg_grid.best_score_, NNReg_grid.best_params_)

0.6743626794638489 {'n_neighbors': 10}

In [ ]:
y_pred = NNReg.predict(X_test)
print(MAE(y_test, y_pred))
print(MSE(y_test, y_pred))

0.3328135403575605
0.28024164467957685

In [ ]:
NNReg_param = {'n_neighbors':[x for x in range(1, 21)]}

NNReg = KNeighborsRegressor()
NNReg_grid = GridSearchCV(NNReg, NNReg_param, cv = 5, refit = True)

NNReg_grid.fit(mmX_train, mmy_train)
NNReg = NNReg_grid.best_estimator_
print(NNReg_grid.best_score_, NNReg_grid.best_params_)

0.6743626794638489 {'n_neighbors': 10}

In [ ]:
mmy_pred = NNReg.predict(mmX_test)
print(MAE(mmy_test, mmy_pred))
print(MSE(mmy_test, mmy_pred))

0.3328135403575605
0.28024164467957685

### Smoothing Splines

In [ ]:
from scipy.interpolate import make_smoothing_spline

make_smoothing_spline(X_train, y_train)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### XGBoost

In [ ]:
xgbReg_param = {'n_estimators':[50*x for x in range(1, 6)], 'max_depth':[3*x for x in range(1, 11)]}

xgbReg = XGBRegressor()
xgbReg_grid = GridSearchCV(xgbReg, xgbReg_param, cv = 5, refit = True)

xgbReg_grid.fit(X_train, y_train)
xgbReg = xgbReg_grid.best_estimator_
print(xgbReg_grid.best_score_, xgbReg_grid.best_params_)

0.7903899246896147 {'max_depth': 3, 'n_estimators': 250}

In [ ]:
y_pred = xgbReg.predict(X_test)

print(MSE(y_test, y_pred))

0.1618506445046498